"""add model_metadata to chat_history

Revision ID: 88d7703fcac9
Revises: 7ab44516e13a
Create Date: 2026-02-21 23:38:07.798516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d7703fcac9'
down_revision = '7ab44516e13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('model_metadata')

    # ### end Alembic commands ###
